openapi: 3.0.3
info:
  title: Banking Microservice Internal API
  version: 1.0.0
  description: Internal APIs for banking microservice operations
paths:
  /internal/transactions:
    get:
      summary: List all transactions from last 24 hours
      description: Internal API to retrieve all transactions made within the last 24 hours
      responses:
        '200':
          description: List of transactions from last 24 hours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        from_account_id:
          type: integer
        to_account_id:
          type: integer
        amount:
          type: number
          format: float
        currency:
          type: string
        created_at:
          type: string
          format: date-time
